name: eventer_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  flutter_switch: ^0.3.2
  flutter_screenutil: ^5.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  dio: ^5.1.1
  jwt_decoder: ^2.0.1
  pretty_dio_logger: ^1.3.1
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1

  skeletons: ^0.0.3
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^4.0.4
  persistent_bottom_nav_bar_v2: ^4.2.8
  readmore: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/google_fonts/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
